version: 2
updates:

  # ğŸ¤– maintain dependencies for bot
  - package-ecosystem: "npm"
    directory: "/bot"
    schedule:
      interval: "monthly"
      time: "16:30"
    reviewers:
      - "sBx99"

  # ğŸŒ maintain dependencies for website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
      time: "11:00"
    reviewers:
      - "sBx99"
